version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
    ports:
      - 8000
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fazon_user
      - POSTGRES_PASSWORD=wsrUU5uqTd3NhVp6CzwxrL3RNgnWfj
      - POSTGRES_DB=fazon_db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/user/web/staticfiles/
      - media_volume:/home/user/web/media/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

volumes:
  postgres_data:
  static_volume:
  media_volume:
